"""Conservative acquired-text triage for archive-discovered media candidates.

This script does NOT make final corpus inclusion/exclusion decisions. It ranks
archive title-trigger candidates for substantive human/reviewer screening using
transparent text signals after acquisition. No stance labels, historical class
targets, model scores, or downstream outcomes are used.

Inputs (generated by the acquisition workflow):
- data/reconstruction/expanded_media_candidates_discovery_direct.csv
- acquisition_output/acquisition_status.csv
- acquisition_output/text/<candidate_id>.txt

Outputs (metadata only; copyrighted full text is not committed):
- data/reconstruction/media_substantive_screen_triage.csv
- data/reconstruction/media_substantive_screen_triage_summary.json
"""
from __future__ import annotations

import csv
import json
import re
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RECON = ROOT / "data" / "reconstruction"
ACQ = ROOT / "acquisition_output"
CANDIDATES = RECON / "expanded_media_candidates_discovery_direct.csv"
ACQ_STATUS = ACQ / "acquisition_status.csv"
TEXT_DIR = ACQ / "text"
OUT = RECON / "media_substantive_screen_triage.csv"
SUMMARY = RECON / "media_substantive_screen_triage_summary.json"

CASE_TERMS = {
    "marikana": re.compile(r"\bmarikana\b", re.I),
    "farlam": re.compile(r"\bfarlam\b", re.I),
    "nkaneng": re.compile(r"\bnkaneng\b", re.I),
    "wonderkop": re.compile(r"\bwonderkop\b", re.I),
    "bapo": re.compile(r"\bbapo(?:-ba-mogale)?\b", re.I),
}
LONMIN = re.compile(r"\blonmin\b", re.I)
ISSUE_TERMS = {
    "strike": re.compile(r"\bstrik(?:e|es|ing|er|ers)\b", re.I),
    "worker": re.compile(r"\b(?:mine\s*)?workers?\b|\bminers?\b", re.I),
    "police": re.compile(r"\bpolice\b|\bsaps\b", re.I),
    "massacre": re.compile(r"\bmassacre\b|\bkill(?:ing|ings|ed)?\b", re.I),
    "commission": re.compile(r"\bcommission\b|\binquiry\b", re.I),
    "housing": re.compile(r"\bhous(?:e|es|ing)\b|\bhostels?\b", re.I),
    "community": re.compile(r"\bcommunit(?:y|ies)\b", re.I),
    "wage": re.compile(r"\bwages?\b|\bpay\b|\bremuneration\b", re.I),
    "social_labour_plan": re.compile(r"\bsocial and labour plan\b|\bslp\b", re.I),
    "compensation": re.compile(r"\bcompensat(?:e|ed|ion)\b|\bdamages\b", re.I),
    "justice": re.compile(r"\bjustice\b|\baccountab(?:ility|le)\b", re.I),
    "union": re.compile(r"\bamcu\b|\bnum\b|\bunion\b", re.I),
}


def read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open(encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def count(pattern: re.Pattern[str], text: str) -> int:
    return len(pattern.findall(text or ""))


def first_words(text: str, n: int = 1200) -> str:
    words = re.findall(r"\S+", text or "")
    return " ".join(words[:n])


candidates = read_csv(CANDIDATES)
status_rows = read_csv(ACQ_STATUS)
status_by_id = {r.get("candidate_id", ""): r for r in status_rows}

rows: list[dict[str, object]] = []
triage_counts: Counter[str] = Counter()
bucket_counts: Counter[str] = Counter()

for candidate in candidates:
    cid = (candidate.get("candidate_id") or "").strip()
    bucket = (candidate.get("prescreen_bucket") or "").strip()
    acq = status_by_id.get(cid, {})
    acq_state = (acq.get("status") or "not_in_acquisition_run").strip()
    text_path = TEXT_DIR / f"{cid}.txt"
    text = text_path.read_text(encoding="utf-8", errors="replace") if text_path.exists() else ""
    early = first_words(text)

    case_counts = {name: count(rx, text) for name, rx in CASE_TERMS.items()}
    case_early_counts = {name: count(rx, early) for name, rx in CASE_TERMS.items()}
    issue_counts = {name: count(rx, text) for name, rx in ISSUE_TERMS.items()}

    case_mentions = sum(case_counts.values())
    case_early_mentions = sum(case_early_counts.values())
    distinct_case_terms = sum(1 for n in case_counts.values() if n > 0)
    issue_mentions = sum(issue_counts.values())
    distinct_issue_terms = sum(1 for n in issue_counts.values() if n > 0)
    lonmin_mentions = count(LONMIN, text)

    if acq_state != "acquired_extracted":
        triage = "manual_review_acquisition_exception"
        rationale = (
            f"Acquisition state is {acq_state}; substantive text screening cannot be completed reliably."
        )
        priority = "high"
    elif bucket == "explicit_case_title_review":
        if case_mentions >= 2 or case_early_mentions >= 1:
            triage = "priority_manual_review_case_signal"
            rationale = (
                "High-specificity case term occurs in the title/URL and is supported by extracted-text case signal; "
                "manual substantive review is still required before inclusion."
            )
            priority = "high"
        else:
            triage = "manual_review_title_text_mismatch"
            rationale = (
                "High-specificity case term occurs in the title/URL but extracted text has weak/no corresponding case signal; "
                "check extraction quality, article framing, and incidental/analogical use."
            )
            priority = "high"
    elif bucket == "lonmin_only_title_review":
        if case_mentions >= 2 and distinct_issue_terms >= 1:
            triage = "priority_manual_review_case_signal"
            rationale = (
                "Lonmin-only title is supported by repeated Marikana-case references plus at least one labour/governance issue signal; "
                "manual substantive review is required."
            )
            priority = "high"
        elif case_mentions >= 1:
            triage = "manual_review_possible_case_signal"
            rationale = (
                "Lonmin-only title contains at least one Marikana-case reference in extracted text, but evidence is insufficient for any automatic decision."
            )
            priority = "medium"
        else:
            triage = "manual_review_lonmin_only_low_case_signal"
            rationale = (
                "Lonmin-only title has no high-specificity Marikana-case term in extracted text. This is a likely source of corporate/financial over-inclusion, "
                "but final exclusion must be made by substantive review rather than this automated triage."
            )
            priority = "low"
    else:
        triage = "manual_review_unexpected_prescreen_bucket"
        rationale = "Candidate has an unexpected prescreen bucket; preserve for manual review."
        priority = "high"

    triage_counts[triage] += 1
    bucket_counts[bucket or "missing"] += 1
    rows.append({
        "candidate_id": cid,
        "title": candidate.get("title", ""),
        "year": candidate.get("year", ""),
        "publisher": candidate.get("publisher", ""),
        "url": candidate.get("url", ""),
        "prescreen_bucket": bucket,
        "acquisition_status": acq_state,
        "text_words": acq.get("text_words", ""),
        "text_sha256": acq.get("text_sha256", ""),
        "lonmin_mentions": lonmin_mentions,
        "case_mentions_total": case_mentions,
        "case_mentions_first_1200_words": case_early_mentions,
        "distinct_case_terms": distinct_case_terms,
        "marikana_mentions": case_counts["marikana"],
        "farlam_mentions": case_counts["farlam"],
        "nkaneng_mentions": case_counts["nkaneng"],
        "wonderkop_mentions": case_counts["wonderkop"],
        "bapo_mentions": case_counts["bapo"],
        "issue_mentions_total": issue_mentions,
        "distinct_issue_terms": distinct_issue_terms,
        "triage_status": triage,
        "review_priority": priority,
        "triage_rationale": rationale,
        "final_inclusion_decision": "",
        "final_decision_reason": "",
    })

if rows:
    with OUT.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)

summary = {
    "triage_type": "non_decisional_substantive_review_prioritisation",
    "candidate_records": len(candidates),
    "triaged_records": len(rows),
    "prescreen_bucket_counts": dict(bucket_counts),
    "triage_status_counts": dict(triage_counts),
    "final_inclusion_decisions_made": 0,
    "important_note": (
        "This triage does not include or exclude records. It only prioritises manual substantive review using transparent acquired-text signals. "
        "Final corpus membership must be recorded separately with an explicit decision reason before freeze."
    ),
}
SUMMARY.write_text(json.dumps(summary, indent=2), encoding="utf-8")
print(json.dumps(summary, indent=2))
